WorkAmount/Controllers/BasicDataController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkAmount.Controllers
{
    public class BasicDataController : BaseController
    {
        public ActionResult DataType()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetData(int pageIndex,int pageSize)
        {
            var temp = db.t_BasicData.Where(n => n.IsDelete == 1).OrderBy(n=>n.ID)
                         .Skip(pageSize * (pageIndex - 1))
                         .Take(pageSize).ToList();
            ViewData["total"] = db.t_BasicData.Where(n => n.IsDelete == 1).Count();
            ViewData["pageindex"] = pageIndex;
            ViewData["pagesize"] = pageSize;

            return PartialView("BasicDataPartial", temp);
        }

        [HttpPost]
        public ActionResult AddData(BasicDataModel model)
        {
            t_BasicData newData = new t_BasicData();
            newData.Name = model.Name;
            newData.Remark = model.Remark;
            newData.IsType = model.IsType;
            newData.IsDelete = 1;

            db.t_BasicData.Add(newData);
            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "添加成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "添加失败"));
            }
        }

        [HttpPost]
        public ActionResult EditData(BasicDataModel model)
        {
            var editData = db.t_BasicData.FirstOrDefault(n => n.ID == model.ID);
            editData.Name = model.Name;
            editData.Remark = model.Remark;
            editData.IsType = model.IsType;;

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "修改成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "修改失败"));
            }
        }

        [HttpPost]
        public ActionResult DelData(int id)
        {
            var editData = db.t_BasicData.FirstOrDefault(n => n.ID == id);
            editData.IsDelete = 0;

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "删除成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "删除失败"));
            }
        }
    }
}

WorkAmount/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WorkAmount.Controllers
{
    public class ProjectController : BaseController
    {
        public ActionResult ProjectList()
        {
            return View();
        }
    }
}

WorkAmount/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;

namespace WorkAmount.Controllers
{
    public class UserController : BaseController
    {
        public ActionResult UserList()
        {
            return View();
        }

        /// <summary>
        /// 获取用户
        /// </summary>
        /// <param name="pageindex"></param>
        /// <param name="pagesize"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetUser(int pageindex, int pagesize)
        {
            var temp = db.t_Users.Where(n => n.IsDelete == 1)
                .OrderBy(n => n.ID)
                .Skip(pagesize * (pageindex - 1))
                .Take(pagesize).ToList();
            ViewData["total"] = db.t_Users.Where(n => n.IsDelete == 1).Count();
            ViewData["pageindex"] = pageindex;
            ViewData["pagesize"] = pagesize;

            int pageIndex = pageindex;//当前页
            int pageSize = pagesize;//显示条数

            return PartialView("UserPartial", temp);
        }

        /// <summary>
        /// 添加用户
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddUser(UsersModel model)
        {
            var loginName = db.t_Users.FirstOrDefault(n => n.LoginName.Equals(model.LoginName));

            if (loginName == null)
            {
                t_Users tbUser = new t_Users();
                tbUser.LoginName = model.LoginName.Trim();
                tbUser.ChineseName = model.ChineseName.Trim();
                tbUser.EnglishName = model.EnglishName.Trim();
                tbUser.Email = model.Email.Trim();
                tbUser.Phone = model.Phone.Trim();
                tbUser.Password = "123456";
                tbUser.IsDelete = 1;
                tbUser.Technology = model.Technology;
                db.t_Users.Add(tbUser);
                try
                {
                    db.SaveChanges();
                    return Json(new MessageData(true, "添加成功"));
                }
                catch (Exception)
                {
                    return Json(new MessageData(false, "添加失败"));
                }
            }
            else
            {
                return Json(new MessageData(true, "用户名已存在"));
            }

        }

        /// <summary>
        /// 修改用户信息
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditUser(UsersModel model)
        {
            var useredit = db.t_Users.FirstOrDefault(n => n.ID == model.ID);

            useredit.LoginName = model.LoginName.Trim();
            useredit.ChineseName = model.ChineseName.Trim();
            useredit.EnglishName = model.EnglishName.Trim();
            useredit.Email = model.Email.Trim();
            useredit.Phone = model.Phone.Trim();
            useredit.Technology = model.Technology;

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "修改成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "修改失败"));
            }
        }

        /// <summary>
        /// 删除用户信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DelUser(int id)
        {
            var user = db.t_Users.FirstOrDefault(n => n.ID == id);
            user.IsDelete = 0;

            try
            {
                db.SaveChanges();
                return Json(new MessageData(true, "删除成功"));
            }
            catch (Exception)
            {
                return Json(new MessageData(false, "删除失败"));
            }
        }


    }
}

WorkAmount/Views/Shared/BasicDataPartial.cshtml
@model List<Model.t_BasicData>
@{ 
    int total = ViewData.GetInt("total");
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        var num = (i % 2 == 0) ? "even" : "odd";
        <tr class=@num >
            <td class="a-center">
                <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" class="flat" name="table_records" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
            </td>
            <td>@item[i].Name</td>
            <td>@item[i].Remark</td>
            <td>
                <a href="javascript:;" data-toggle="modal" data-target="#myModal" onclick="EditModal(@(i+1),@item[i].ID)">修改</a>&nbsp;&nbsp;
                <a href="javascript:;" onclick="DelModal(@item[i].ID)">删除</a>
            </td>
        </tr>
    }
}
else
{
    <tr class="even">
        <td class="a-center ">
            <div class="icheckbox_flat-green" style="position: relative;"><input type="checkbox" class="flat" name="table_records" style="position: absolute; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>
        </td>
        <td  colspan="3">无法找到信息</td>
    </tr>
}

<script>
    var total = @total;
</script>

WorkAmount/Views/Shared/UserPartial.cshtml
@model List<Model.t_Users>
@{
    int total = ViewData.GetInt("total");
    int pageindex = ViewData.GetInt("pageindex");
    int pagesize = ViewData.GetInt("pagesize");
}

@if (Model != null && Model.Count > 0)
{
    var item = Model;
    for (int i = 0; i < Model.Count; i++)
    {
        <tr>
            <th class="hidden">@item[i].ID</th>
            <td>@item[i].LoginName</td>
            <td>@item[i].ChineseName</td>
            <td>@item[i].EnglishName</td>
            <td>@item[i].Email</td>
            <td>@item[i].Phone</td>
            <td>@item[i].Technology</td>
            <td>
                
                <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal" onclick="EditModal(@(i+1),@item[i].ID)">修改</a>&nbsp;&nbsp;
                <a href="javascript:void(0)" onclick="DelModal(@item[i].ID)">删除</a>
            </td>
        </tr>
    }
}

<tr class="hidden"><th id="total">@total</th></tr>

WorkAmount/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>日报系统</title>

    <!-- Bootstrap -->
    <link href="~/Content/CSS/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/Content/CSS/font-awesome.min.css" rel="stylesheet" />

    @*<!-- NProgress -->
        <link href="../vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="../vendors/iCheck/skins/flat/green.css" rel="stylesheet">

        <!-- bootstrap-progressbar -->
        <link href="../vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="../vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
        <!-- bootstrap-daterangepicker -->
        <link href="../vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">*@

    <!-- Custom Theme Style -->
    <link href="~/Content/CSS/custom.min.css" rel="stylesheet" />
    <link href="~/Content/CSS/style.css" rel="stylesheet" />
    <link href="~/Content/CSS/jquery-confirm.min.css" rel="stylesheet" />
    <link href="~/Content/CSS/jquery.jedate.css" rel="stylesheet" />
    <style>
        a:visited {
            background: none;
        }

        .nav-md #menuMask .col-md-3.left_col,
        .nav-sm #menuMask .col-md-3.left_col {
            height: 230px;
            width: 230px;
            padding: 0;
            position: fixed;
            bottom: 0;
            display: -ms-flexbox;
            z-index: 0;
        }

        .nav-sm #menuMask .col-md-3.left_col {
            width: 70px
        }

        .page-info {
            float: left;
            padding: 3px 1px;
        }

        .required {
            color: #ff5300;
        }

        .txt-overflow {
            overflow-x: hidden;
            resize: none;
        }

        .page-number {
            float: right;
            padding: 0;
            margin-right: -10px;
        }

            .page-number span {
                padding: 0.25em 0.75em;
                margin-left: 2px;
                text-align: center;
                text-decoration: none;
                cursor: pointer;
                color: #333;
                border-radius: 2px;
                box-sizing: border-box;
            }

            .page-number a {
                padding: 0.25em 0.75em;
                margin-left: 2px;
                text-align: center;
                text-decoration: none;
                cursor: pointer;
                color: #333;
                border: 1px solid #808080;
                border-radius: 2px;
                box-sizing: border-box;
            }
    </style>
    <!-- jQuery -->
    <script src="~/Content/JS/jquery2.1.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/JS/bootstrap.min.js"></script>
    <script src="~/Content/JS/parsley.min.js"></script>
    <script src="~/Content/JS/jquery-confirm.min.js"></script>
    <script src="~/Content/JS/script.js"></script>
    <script src="~/Content/JS/jquery.jedate.min.js"></script>

</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>SHINETECH</span></a>
                    </div>

                    <div class="clearfix"></div>

                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-edit"></i> 日报填写 </a>
                                </li>
                                <li>
                                    <a><i class="fa fa-home"></i> 个人统计 <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="index.html">Dashboard</a></li>
                                        <li><a href="index2.html">Dashboard2</a></li>
                                        <li><a href="index3.html">Dashboard3</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="@Url.Action("UserList","User")"><i class="fa fa-bar-chart-o"></i>人员管理</a>

                                </li>
                                <li>
                                    <a href="@Url.Action("ProjectList", "Project")"><i class="fa fa-clone"></i>项目信息</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("DataType", "BasicData")"><i class="fa fa-clone"></i>基础数据</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                </div>
            </div>
            <div id="menuMask">
                <div class="col-md-3 left_col"></div>
            </div>


            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    John Doe
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> 个人信息</a></li>
                                    <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> 退出</a></li>
                                </ul>
                            </li>

                            @*<li role="presentation" class="dropdown">
                                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-envelope-o"></i>
                                        <span class="badge bg-green">6</span>
                                    </a>
                                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                        <li>
                                            <a>
                                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <div class="text-center">
                                                <a>
                                                    <strong>See All Alerts</strong>
                                                    <i class="fa fa-angle-right"></i>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </li>*@
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="containers">
                    @RenderBody()
                </div>
            </div>
            @*<div class="right_col" role="main">
                    @RenderBody()
                </div>*@
            <!-- /page content -->
        </div>
    </div>


    <!-- Custom Theme Scripts -->
    <script src="~/Content/JS/custom.min.js"></script>
    @*<!-- FastClick -->
        <script src="../vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="../vendors/nprogress/nprogress.js"></script>
        <!-- Chart.js -->
        <script src="../vendors/Chart.js/dist/Chart.min.js"></script>
        <!-- gauge.js -->
        <script src="../vendors/gauge.js/dist/gauge.min.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="../vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="../vendors/iCheck/icheck.min.js"></script>
        <!-- Skycons -->
        <script src="../vendors/skycons/skycons.js"></script>
        <!-- Flot -->
        <script src="../vendors/Flot/jquery.flot.js"></script>
        <script src="../vendors/Flot/jquery.flot.pie.js"></script>
        <script src="../vendors/Flot/jquery.flot.time.js"></script>
        <script src="../vendors/Flot/jquery.flot.stack.js"></script>
        <script src="../vendors/Flot/jquery.flot.resize.js"></script>
        <!-- Flot plugins -->
        <script src="../vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
        <script src="../vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
        <script src="../vendors/flot.curvedlines/curvedLines.js"></script>
        <!-- DateJS -->
        <script src="../vendors/DateJS/build/date.js"></script>
        <!-- JQVMap -->
        <script src="../vendors/jqvmap/dist/jquery.vmap.js"></script>
        <script src="../vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
        <script src="../vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="../vendors/moment/min/moment.min.js"></script>
        <script src="../vendors/bootstrap-daterangepicker/daterangepicker.js"></script>*@




</body>
</html>